//@version=6
indicator("RSI + Stochastic", shorttitle="RSI + Stoch", overlay=false)

// ==========================================
// INPUT
// ==========================================
// RSI
rsiGroup     = "RSI"
rsiLength    = input.int(14, title="RSI Length", minval=1, group=rsiGroup)
rsiSource    = input.source(close, title="RSI Source", group=rsiGroup)

// Stochastic
stochGroup   = "Stochastic"
stochK       = input.int(14, title="Stoch %K Length", minval=1, group=stochGroup)
stochD       = input.int(3, title="Stoch %D Smoothing", minval=1, group=stochGroup)
stochSmooth  = input.int(3, title="Stoch %K Smoothing", minval=1, group=stochGroup)

// Overbought / Oversold
levelsGroup  = "Overbought / Oversold"
overbought_1   = input.int(80, title="Overbought Level 1", minval=1, maxval=100, group=levelsGroup)
oversold_1     = input.int(20, title="Oversold Level 1", minval=1, maxval=100, group=levelsGroup)
overbought_2   = input.int(70, title="Overbought Level 2", minval=1, maxval=100, group=levelsGroup)
oversold_2     = input.int(30, title="Oversold Level 2", minval=1, maxval=100, group=levelsGroup)

// ==========================================
// CALCULATION
// ==========================================
// RSI
rsiVal = ta.rsi(rsiSource, rsiLength)

// Stochastic (%K dan %D)
rawK = ta.stoch(close, high, low, stochK)
kVal = ta.sma(rawK, stochSmooth)
dVal = ta.sma(kVal, stochD)

// ==========================================
// VISUALIZATION
// ==========================================
hline(overbought_1, "OB 1", color=color.gray, linestyle=hline.style_dashed)
hline(overbought_2, "OB 2", color=color.gray, linestyle=hline.style_dashed)
hline(50, "Middle Line", color=color.new(color.gray, 50), linestyle=hline.style_dotted)
hline(oversold_1, "OS 1", color=color.gray, linestyle=hline.style_dashed)
hline(oversold_2, "OS 2", color=color.gray, linestyle=hline.style_dashed)

plot(rsiVal, title="RSI Line", color=color.blue, linewidth=2)
plot(kVal, title="Stoch %K", color=color.purple, linewidth=1)
plot(dVal, title="Stoch %D", color=color.orange, linewidth=1)
